name: Update ipv6 Addresses

on:
  schedule:
    - cron: '*/30 * * * *'  # 每隔三十分钟运行一次
  workflow_dispatch: # 允许手动触发

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  update-ipv6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ env.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python process_ipv6.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipv6.txt
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update IPv6 addresses [$(date)]"
            git push
          else
            echo "No changes to commit."
          fi
